# Generated by Django 3.1.7 on 2021-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_auto_20210304_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
